
package tpractico6;

import java.util.TreeSet;

/**
 *
 * @author Usuario
 */
public class menuGeneral extends javax.swing.JFrame {

   public static TreeSet<Producto>lista=new TreeSet<>();
    public menuGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        mjProductos = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmPorPrecio = new javax.swing.JMenuItem();
        jmPorNombre = new javax.swing.JMenuItem();
        jmPorRubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 268, Short.MAX_VALUE)
        );

        jmAdministracion.setText("Administracion ");

        mjProductos.setText("Productos");
        mjProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mjProductosActionPerformed(evt);
            }
        });
        jmAdministracion.add(mjProductos);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmPorPrecio.setText("Por Precio");
        jmPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmPorPrecio);

        jmPorNombre.setText("Por Nombre");
        jmPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmPorNombre);

        jmPorRubro.setText("Por Rubro");
        jmPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmPorRubro);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mjProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mjProductosActionPerformed
       escritorio.removeAll();
       escritorio.repaint();
       Productos pif= new Productos();
       pif.setVisible(true);
       escritorio.add(pif);
       escritorio.moveToFront(pif);
       
    }//GEN-LAST:event_mjProductosActionPerformed

    private void jmPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorPrecioActionPerformed
      escritorio.removeAll();
    escritorio.repaint();
    ConsultasPorRubro gdp=new ConsultasPorRubro();
    gdp.setVisible(true);
    escritorio.add(gdp);
    escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jmPorPrecioActionPerformed

    private void jmPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorRubroActionPerformed
    escritorio.removeAll();
    escritorio.repaint();
    ConsultasPorRubro gdp=new ConsultasPorRubro();
    gdp.setVisible(true);
    escritorio.add(gdp);
    escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jmPorRubroActionPerformed

    private void jmPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorNombreActionPerformed
    escritorio.removeAll();
    escritorio.repaint();
    PorNombre gdp=new PorNombre();
    gdp.setVisible(true);
    escritorio.add(gdp);
    escritorio.moveToFront(gdp);
    }//GEN-LAST:event_jmPorNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmPorNombre;
    private javax.swing.JMenuItem jmPorPrecio;
    private javax.swing.JMenuItem jmPorRubro;
    private javax.swing.JMenuItem mjProductos;
    // End of variables declaration//GEN-END:variables
}
